### ISSUE TITLE
About training Scaffnet using virtual KITTI dataset

### ISSUE THREAD

**Issue by lyysl** [alexklwong/learning-topology-synthetic-data#3]
I got an error when training Scaffnet using virtual KITTI dataset.
Is there a bug using this dataset? Thank you.

`tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[2,288,0] = -2147483648 is not in [0, 256)
         [[{{node scaffnet/GatherV2_3}}]]`

**Comment by alexklwong** [comment]
Seems like an error with the data

indices[2,288,0] = -2147483648

Can you paste the entire stack trace?

**Comment by lyysl** [comment]
` sh bash/train_scaffnet_vkitti.sh
Dataloader settings:
n_batch=1  n_height=320  n_width=768
min_dataset_depth=1.50  max_dataset_depth=80.00
crop_type=bottom
random_horizontal_crop=True  random_vertical_crop=True
random_horizontal_flip=False

Network settings:
network_type=scaffnet32  n_parameter=1485765
activation_func=leaky_relu
n_filter_output=32

Spatial pyramid pooling settings:
pool_kernel_sizes_spp=[5, 7, 9, 11]
n_convolution_spp=3  n_filter_spp=32

Depth prediction settings:
min_predict_depth=1.50  max_predict_depth=100.00

Training settings:
n_sample=4252  n_epoch=50  n_step=212600
loss_func=l1_norm
learning_schedule=[0 (0) : 4.0E-04, 8 (34016) : 3.0E-04, 20 (85040) : 2.0E-04, 30 (127560) : 1.0E-04, 50 (212600)]

Depth evaluation settings:
min_evaluate_depth=0.00  max_evaluate_depth=100.00

Checkpoint settings:
checkpoint_path=trained_scaffnet/vkitti/scaffnet32
restore_path=None

Begin training...
Traceback (most recent call last):
  File "/home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[101,256] = -2147483648 is not in [0, 256)
         [[{{node scaffnet/GatherV2_3}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/train_scaffnet.py", line 147, in <module>
    n_thread=args.n_thread)
  File "/mnt/c/myProject/phd/what/others/learning-topology-synthetic-data-master/src/scaffnet.py", line 296, in train
    _, loss_value, train_summary = session.run([gradients, loss, model_summary])
  File "/home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[101,256] = -2147483648 is not in [0, 256)
         [[node scaffnet/GatherV2_3 (defined at /home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'scaffnet/GatherV2_3':
  File "src/train_scaffnet.py", line 147, in <module>
    n_thread=args.n_thread)
  File "/mnt/c/myProject/phd/what/others/learning-topology-synthetic-data-master/src/scaffnet.py", line 172, in train
    loss_func=loss_func)
  File "/mnt/c/myProject/phd/what/others/learning-topology-synthetic-data-master/src/scaffnet_model.py", line 165, in __init__
    self.loss = self.build_loss()
  File "/mnt/c/myProject/phd/what/others/learning-topology-synthetic-data-master/src/scaffnet_model.py", line 203, in build_loss
    vmax=0.20)], axis=1),
  File "/mnt/c/myProject/phd/what/others/learning-topology-synthetic-data-master/src/log_utils.py", line 108, in gray2color
    return colorize(gray, cm)
  File "/mnt/c/myProject/phd/what/others/learning-topology-synthetic-data-master/src/log_utils.py", line 76, in colorize
    value = tf.gather(colormap, indices)
  File "/home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 3956, in gather
    params, indices, axis, name=name)
  File "/home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 4082, in gather_v2
    batch_dims=batch_dims, name=name)
  File "/home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/simon/miniconda3/envs/scaffnet_env/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
`

**Comment by alexklwong** [comment]
It seems like it is potentially a tensorflow specific problem in the gather operation. Which version are you using?

Also, this is particularly isolated to the visualization tensorboard summary. So in the short term, I would suggest commenting out:

https://github.com/alexklwong/learning-topology-synthetic-data/blob/master/src/scaffnet_model.py#L192-L204

or if you were to remove the call to the gray2color function, it will automatically default to grayscale visualizations.

**Comment by lyysl** [comment]
Thank you. It is working now by commenting the L192-L204.
